appname = yshop
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn =
api_url = https://goapi.yixiang.co
#忽略URL
ignore_urls = "/admin/auth/login,/admin/auth/captcha"

[dev]
#数据库配置
mysqluser = "root"
mysqlpass = "root"
mysqlhost = "localhost"
mysqlport = 3306
mysqldb = "yshop_go"
db_max_idle_conn = 30
db_max_open_open = 100
maxmemory = 1<<22

#redis
redis_host = 127.0.0.1:6379
redis_pwd =

#日志等级 debug
logLevel = 7

jwt_token = 1BD6C43CA0BBF4B7ABA5E486D6A5AA2D

[prod]
#数据库配置
mysqluser = "root"
mysqlpass = "root"
mysqlhost = "localhost"
mysqlport = 3306
mysqldb = "yshop_go"
db_max_idle_conn = 30
db_max_open_open = 100
maxmemory = 1<<22

#redis
redis_host = 127.0.0.1:6379
redis_pwd =

#日志等级 debug
logLevel = 4

jwt_token = 1BD6C43CA0BBF4B7ABA5E486D6A5AA2D

